
--Modify SQL - if result is zero show  null if not zero show result - for all column
SELECT
  D.CUIIO,
  D.CUATM,
  MAX(CASE WHEN D.CAPITOL = 100 AND D.RIND NOT IN ('-','ER','00') THEN D.RIND ELSE NULL END) AS CAP_SR_RIND,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.1.1') THEN D.COL1 ELSE NULL END) AS  R_1_1_1,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.1.2') THEN D.COL1 ELSE NULL END) AS  R_1_1_2,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.3.1') THEN D.COL1 ELSE NULL END) AS  R_1_3_1,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.3.2') THEN D.COL1 ELSE NULL END) AS  R_1_3_2,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.3.3') THEN D.COL1 ELSE NULL END) AS  R_1_3_3,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.3.4') THEN D.COL1 ELSE NULL END) AS  R_1_3_4,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.1') THEN D.COL1 ELSE NULL END) AS  R_1_5_1,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.2') THEN D.COL1 ELSE NULL END) AS  R_1_5_2,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.3') THEN D.COL1 ELSE NULL END) AS  R_1_5_3,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.4') THEN D.COL1 ELSE NULL END) AS  R_1_5_4,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.5') THEN D.COL1 ELSE NULL END) AS  R_1_5_5,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.6') THEN D.COL1 ELSE NULL END) AS  R_1_5_6,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.5.7') THEN D.COL1 ELSE NULL END) AS  R_1_5_7,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.1') THEN D.COL1 ELSE NULL END) AS  R_1_7_1,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.2') THEN D.COL1 ELSE NULL END) AS  R_1_7_2,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.3') THEN D.COL1 ELSE NULL END) AS  R_1_7_3,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.4') THEN D.COL1 ELSE NULL END) AS  R_1_7_4,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.5') THEN D.COL1 ELSE NULL END) AS  R_1_7_5,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.6') THEN D.COL1 ELSE NULL END) AS  R_1_7_6,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.7') THEN D.COL1 ELSE NULL END) AS  R_1_7_7,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.8.1') THEN D.COL1 ELSE NULL END) AS  R_1_8_1,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.8.2') THEN D.COL1 ELSE NULL END) AS  R_1_8_2,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.8.3') THEN D.COL1 ELSE NULL END) AS  R_1_8_3,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.8.4') THEN D.COL1 ELSE NULL END) AS  R_1_8_4,
  MAX(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.8.2') THEN D.COL1 ELSE NULL END) AS  R_1_8_2,
  MAX(CASE WHEN D.CAPITOL = 1044 AND D.RIND IN ('4.2') THEN D.COL31 ELSE NULL END) AS  R_4_2
  
  FROM 
  CIS2.VW_DATA_ALL D  
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  D.FORM IN (48)  

  
GROUP BY  
  D.CUIIO,
  D.CUATM