
CREATE TABLE user_bancu.F_XML_FORMS
as 

SELECT F.*
FROM F_XML_FORMS f
WHERE

 f.DATA_REG >= TO_DATE('04/01/2025 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
  AND f.FORM_TYPE = 'inov1'
  AND f.STATUS = 5
  
--  ORDER BY
--  f.DATA_REG DESC 