SELECT 
 CASE       
     WHEN 
    (CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.1.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 OR
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.5.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 )AND
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.7.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 AND
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.9.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))=0
     THEN 'Completati Cap.1 Rindurile 1.9'       
END  AS REZULTAT 
 
FROM
  CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS=-1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1)AND
  
   D.FORM IN(48) 

HAVING
   ((CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.1.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 OR
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.5.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 )AND
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.7.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))>=1 AND
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1040) AND D.RIND LIKE ('1.9.%') THEN CIS2.NVAL(D.COL1) ELSE 0 END))=0)
  