--SQL Oracle
--Modify this sql Oracle
--For each column - if the result is zero, it should be null
SELECT DISTINCT
      D.CUIIO,
      R.DENUMIRE,
      R.CUATM,
      D.CAEM2,
      R.IDNO,
      MAX(CASE WHEN  D.CAPITOL IN (100) AND D.RIND NOT IN ('ER','-' )THEN D.RIND ELSE NULL  END ) AS CAP_SR,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.1.1' )THEN D.COL1 ELSE NULL  END ) AS R_1_1_1,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.1.2' )THEN D.COL1 ELSE NULL  END ) AS R_1_1_2,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.3.1' )THEN D.COL1 ELSE NULL  END ) AS R_1_3_1,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.3.2' )THEN D.COL1 ELSE NULL  END ) AS R_1_3_2,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.3.3' )THEN D.COL1 ELSE NULL  END ) AS R_1_3_3,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.3.4' )THEN D.COL1 ELSE NULL  END ) AS R_1_3_4,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.1' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_1,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.2' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_2,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.3' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_3,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.4' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_4,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.5' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_5,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.6' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_6,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.5.7' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_7,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.1' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_1,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.2' )THEN D.COL1 ELSE NULL  END ) AS R_1_5_2,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.3' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_3,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.4' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_4,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.5' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_5,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.6' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_6,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.7.7' )THEN D.COL1 ELSE NULL  END ) AS R_1_7_7,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.8.1' )THEN D.COL1 ELSE NULL  END ) AS R_1_8_1,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.8.2' )THEN D.COL1 ELSE NULL  END ) AS R_1_8_2,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.8.3' )THEN D.COL1 ELSE NULL  END ) AS R_1_8_3,
      MAX(CASE WHEN  D.CAPITOL IN (1040) AND D.RIND  IN ('1.8.4' )THEN D.COL1 ELSE NULL  END ) AS R_1_8_4,
      TRIM(MAX(CASE WHEN  D.CAPITOL IN (1044) AND D.RIND  IN ('4.2' )THEN  TRIM(D.COL31) ELSE NULL  END ))   AS R_4_2
      
      
      
      
      
  
       FROM
      CIS2.VW_DATA_ALL D  INNER JOIN 
                          CIs2.RENIM R ON R.CUIIO = D.CUIIO  AND R.CUIIO_VERS = D.CUIIO_VERS 
    WHERE
      D.PERIOADA IN (:pPERIOADA) AND 
      D.FORM_VERS = :pFORM_VERS     AND   
      D.FORM= :pFORM     AND    
      (:pID_MDTABLE=:pID_MDTABLE) AND
      D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  AND 
      D.FORM IN (48)
      --AND capitol=1040 AND  capitol_vers=2013
  --    AND D.CUIIO = 400053
    GROUP BY
      D.CUIIO,
      R.DENUMIRE,
      R.CUATM,
      D.CAEM2,
      R.IDNO
      
      
      
      ORDER BY
      R.CUATM
      
  --    ) D
      