SELECT
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) + 
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) +
  (  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) +
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND NVAL(D.COL1) = 1  THEN D.CUIIO END))
  
  AS COL1,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) AS COL3,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) +
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) AS COL4 
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.RIND IN ('1.1.1','1.1.2')
  AND D.CAEM2 NOT LIKE 'A%'