SELECT

D.CUIIO,
R.DENUMIRE,
R.CUATM,
MC.DEN_SHORT,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3    


FROM
  CIS2.VW_DATA_ALL D  INNER JOIN CIS2.MD_CAPITOL MC ON  D.CAPITOL = MC.CAPITOL AND D.CAPITOL_VERS = MC.CAPITOL_VERS 
                      INNER JOIN CIS2.RENIM  R ON  D.CUIIO = R.CUIIO  AND D.CUIIO_VERS  = R.CUIIO_VERS 

WHERE
  (D.PERIOADA=:PERIOADA) AND
   D.FORM IN(48)
  
GROUP BY
D.CUIIO,
R.DENUMIRE,
R.CUATM,
MC.DEN_SHORT,
D.RIND


ORDER BY
 D.CUIIO,
 MC.DEN_SHORT,
 D.RIND