SELECT 
DISTINCT 
  CUIIO,
  DENUMIRE, 
  CUATM,
  CAEM2
  
  FROM 


(


SELECT 

  D.CUIIO,
  R.DENUMIRE, 
  R.CUATM,
  R.CAEM2,
  CP.CAPITOL, 
  CP.DEN_SHORT,
  C.CODUL,
  C.FULL_CODE,
  D.RIND,
  SUM(D.COL1) AS COL1,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4
  
 
 
 FROM 
  CIS2.VW_DATA_ALL D
            
  
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
                    
                    INNER JOIN MD_CAPITOL CP ON CP.CAPITOL = D.CAPITOL AND CP.CAPITOL_VERS = D.CAPITOL_VERS 
                    INNER JOIN CIS2.VW_CL_CUATM C  ON  C.CODUL = D.CUATM
                    
                     
  WHERE

  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM       
  
--  AND D.CAPITOL||'.'||D.RIND IN ('1041.2.1.1','1041.2.1.2') AND D.COL1=1  

 
   
  

GROUP BY
  D.CUIIO,
  R.DENUMIRE, 
  R.CUATM,
  R.CAEM2,
  CP.CAPITOL, 
  CP.DEN_SHORT,
  C.CODUL,
  C.FULL_CODE,
  D.RIND
  
  
  
  HAVING

 (CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1047.8.1.1') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1047.8.1.2') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1047.8.1.3') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1047.8.1.4') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+

  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1046.7.1.1') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1046.7.1.2') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1046.7.1.3') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1042.3.1.1') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1042.3.1.2') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1042.3.1.3') AND D.COL1=1 THEN D.COL1 ELSE NULL END)))=0
  
   AND
    
 (CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.1.1') AND D.COL1=1 THEN D.COL1 ELSE NULL END))+
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.1.2') AND D.COL1=1 THEN D.COL1 ELSE NULL END)))>=1
  
  
  ORDER BY 
  C.FULL_CODE,
  D.CUIIO,
  CP.CAPITOL,
  D.RIND
  
  
  )


ORDER BY 
CUIIO 
  
  